theme: jekyll-theme-minimal
title: Sreelekha S
ORCID Profile-orcid.org/0000-0002-5455-5023: https://orcid.org/0000-0002-5455-5023

DBLP Bibliography Profile: https://dblp.org/pid/184/9122.html

GoogleScholar Profile: http://scholar.google.co.in/citations?user=3gLsq9IAAAAJ&hl=en

ResearcherID Profile: https://publons.com/researcher/1375407/sreelekha-s/

Researchgate Profile: https://www.researchgate.net/profile/Sreelekha_S2

Academia.edu Profile: https://iitbombay.academia.edu/SreelekhaS

LinkedIn Profile: https://in.linkedin.com/in/sreelekha-s-nair-68804617

Publons Profile: https://publons.com/researcher/1375407/sreelekha-s/

Facebook Profile: https://www.facebook.com/public/Sreelekha-S-Nair
